-- Criação do banco de dados
-- CREATE DATABASE efood;

-- TABELA DE CLIENTES
CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL,
    endereco VARCHAR(500) NOT NULL
);

-- TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    preco DECIMAL(10,2) NOT NULL CHECK (preco > 0),
    categoria VARCHAR(100) NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE
);

-- TABELA DE PEDIDOS
CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL CHECK (valor_total >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE'
        CHECK (
            status IN (
                'PENDENTE',
                'CONFIRMADO',
                'PREPARANDO',
                'PRONTO',
                'EM_ENTREGA',
                'ENTREGUE',
                'CANCELADO'
            )
        ),
    endereco_entrega VARCHAR(500) NOT NULL,
    data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
);

-- TABELA DE ITENS DO PEDIDO
CREATE TABLE IF NOT EXISTS itens_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    preco_unitario DECIMAL(10,2) NOT NULL CHECK (preco_unitario > 0),
    CONSTRAINT fk_item_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedidos(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_item_produto
        FOREIGN KEY (produto_id)
        REFERENCES produtos(id)
);

-- DADOS DE EXEMPLO
INSERT INTO clientes (nome, email, telefone, endereco)
VALUES
('João Silva', 'joao@email.com', '11999990000', 'Rua das Flores, 123'),
('Maria Souza', 'maria@email.com', '11988880000', 'Av. Brasil, 456');

INSERT INTO produtos (nome, descricao, preco, categoria, disponivel)
VALUES
('Pizza Margherita', 'Pizza com molho de tomate, mussarela e manjericão', 39.90, 'Pizzas', TRUE),
('Pizza Calabresa', 'Pizza com calabresa e cebola', 42.90, 'Pizzas', TRUE),
('Hambúrguer Clássico', 'Pão, carne, queijo, alface e tomate', 29.90, 'Lanches', TRUE),
('Refrigerante 600ml', 'Refrigerante gelado', 8.90, 'Bebidas', TRUE),
('Suco Natural', 'Suco de laranja natural 500ml', 12.90, 'Bebidas', TRUE);
